### ISSUE TITLE
이메일 인증 발송 실패

### ISSUE THREAD

**Issue by sunrabbit123** [semicolondsm/DSM_Auth_Backend_V2#108]
![image](https://user-images.githubusercontent.com/64676070/123590126-2f118900-d825-11eb-8480-ad584ea8679e.png)

이메일 인증 발송 실패 에러가 나타나는데, 

혹여나 DSM의 이메일만 사용이 되거나
이메일 서버가 종료되었나요?

**Comment by sunrabbit123** [comment]
추가적으로
@gsm.hs.kr, @gmail.com 둘 다 안되네요

**Comment by jeongjiwoo0522** [comment]
네 현재는 대마고 @dsm.hs.kr 이메일만 회원가입이 가능합니다. 
혹시 DSM_Auth 서비스를 사용할 계획이신가요 ?

**Comment by sunrabbit123** [comment]
사이트가 있다보니 시도를 하였는데, 안되어서 이슈를 남겼을뿐입니다.
정보 감사드립니다 :D
